name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  DOCKERHUB_SLUG: thesnallygaster/naemon-docker

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta (ubuntu)
        id: meta-ubuntu
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
          tags: |
            type=match,pattern=(.*),group=1
            type=match,pattern=(.*)-.*,group=1
            type=ref,event=pr
            type=edge
          labels: |
            org.opencontainers.image.title=naemon-docker
            org.opencontainers.image.description=Dockerized installation of naemon
            org.opencontainers.image.vendor=thesnallygaster
      -
        name: Docker meta (alpine)
        id: meta-alpine
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
          tags: |
            type=match,pattern=(.*),group=1,suffix=-alpine
            type=match,pattern=(.*)-.*,group=1,suffix=-alpine
            type=ref,event=pr,suffix=-alpine
            type=edge,suffix=-alpine
          labels: |
            org.opencontainers.image.title=naemon-docker
            org.opencontainers.image.description=Dockerized installation of naemon
            org.opencontainers.image.vendor=thesnallygaster
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        uses: docker/bake-action@v5
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta-ubuntu.outputs.bake-file }}
            ${{ steps.meta-alpine.outputs.bake-file }}
          targets: image-all,image-all-alpine
          push: ${{ github.event_name != 'pull_request' }}
      -
        name: Check manifest (ubuntu)
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{ env.DOCKERHUB_SLUG }}:${{ steps.meta-ubuntu.outputs.version }}
      -
        name: Check manifest (alpine)
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{ env.DOCKERHUB_SLUG }}:${{ steps.meta-alpine.outputs.version }}
      -
        name: Inspect (ubuntu)
        if: github.event_name != 'pull_request'
        run: |
          docker pull ${{ env.DOCKERHUB_SLUG }}:${{ steps.meta-ubuntu.outputs.version }}
          docker image inspect ${{ env.DOCKERHUB_SLUG }}:${{ steps.meta-ubuntu.outputs.version }}
      -
        name: Inspect (alpine)
        if: github.event_name != 'pull_request'
        run: |
          docker pull ${{ env.DOCKERHUB_SLUG }}:${{ steps.meta-alpine.outputs.version }}
          docker image inspect ${{ env.DOCKERHUB_SLUG }}:${{ steps.meta-alpine.outputs.version }}
