name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  BUILD_TAG: naemon:test
  CONTAINER_NAME: naemon

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build
        uses: docker/bake-action@v5
        with:
          targets: image-local
        env:
          DEFAULT_TAG: ${{ env.BUILD_TAG }}
      -
        name: Start
        run: |
          docker compose up -d
        working-directory: test
        env:
          NAEMON_IMAGE: ${{ env.BUILD_TAG }}
          NAEMON_CONTAINER: ${{ env.CONTAINER_NAME }}
      -
        name: Check container logs
        uses: crazy-max/.github/.github/actions/container-logs-check@main
        with:
          container_name: ${{ env.CONTAINER_NAME }}
          log_check: "Successfully launched command file worker"
          timeout: 120
      -
        name: Logs
        if: always()
        run: |
          docker compose logs
        working-directory: test
        env:
          NAEMON_IMAGE: ${{ env.BUILD_TAG }}
          NAEMON_CONTAINER: ${{ env.CONTAINER_NAME }}
